import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import './globals.css'
import { Toaster } from "@/components/ui/sonner";
import { WorkspaceProvider } from '@/hooks/use-current-workspace';
import { ModalProvider } from '@/providers/modal-provider'
import { QueryProvider } from '@/providers/query-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'QentSolutions App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <WorkspaceProvider>
        <QueryProvider>
            <html lang="en">
          <body className={inter.className}>
            <Toaster />
            <ModalProvider />
            {children}
          </body>
        </html>
        </QueryProvider>
      </WorkspaceProvider>
    </SessionProvider>
  )
}